version: '3'

services:
  app:
    image: 'car-service-app:latest'
    build:
      context: .
      args:
        SPRING_PROFILE: docker
    container_name: app
    depends_on:
      - db
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env

  db:
    image: 'postgres:14.6'
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
